baseURL = "https://zt6220493.github.io/yunqi/"
languageCode = "zh-CN"
title = "zh-blog"
theme = "hugo-lamp"
googleAnalytics = "UA-XXX-X"          # Google Analytics UA number

[params]
  mainSections = ["posts"]
  subtitle = "Lake And Ocean"
  author = "Zh"
  logo = "/yunqi/img/avatar.jpg"
  description = "A light responsive Hugo AMP theme for blogger"
  paginate = 10

  # Publisher
  ## adsensePublisher = "ca-pub-XXX"    # Required if you want to include Google Adsense
  adsenseSlot = "XXX"                   # Required slot to display ads
  adsenseSlotSticky = "XXX"             # Enables sticky ads feature, value maybe the same with adsenseSlot, remove if you don't want display sticky ads

  # SEO configs
  seotitle = "Hugo Blog Title (SEO Version)"
  googleSiteVerification = "google_site_verification_code"    # Google Webmaster
  msValidate = "bing_site_verification_code"                  # Bing Webmaster

  # Social networks
  email = "1165727479@qq.com"
  github = "zt6220493"

[taxonomies]
  tag = "tags"
  category = "categories"
  archive = "archives"

[[menu.main]]
  name = "文章"
  weight = 1
  identifier = "post"
  url = "/post/"
[[menu.main]]
  name = "归档"
  weight = 2
  identifier = "archives"
  url = "/archives/"
[[menu.main]]
  name = "分类"
  weight = 3
  identifier = "categories"
  url = "/categories/"
[[menu.main]]
  name = "标签"
  weight = 4
  identifier = "tags"
  url = "/tags/"

